##This code is used to generate my map and table 2.

```{r}
addresstable <- read.csv("new data/addresstable.csv")
#Rename the columns
colnames(addresstable) <- c("State", "IncidentNO", "Other","Firefighter","Cause","Street","City", "ZIP","year")
```



```{r}
#Replace the causes number by their actual meanings
addresstable$Cause[is.na(addresstable$Cause)]<- "None"
addresstable[addresstable$Cause == 1, ][,"Cause"] <- "Intentional"
addresstable[addresstable$Cause == 2, ][,"Cause"] <- "Playing with Heat Source"
addresstable[addresstable$Cause == 3, ][,"Cause"] <- "Smoking"
addresstable[addresstable$Cause == 4, ][,"Cause"] <- "Heating"
addresstable[addresstable$Cause == 5, ][,"Cause"] <- "Cooking"

addresstable[addresstable$Cause == 6, ][,"Cause"] <- "Electrical Malfunction"
addresstable[addresstable$Cause == 7, ][,"Cause"] <- "Appliances"
addresstable[addresstable$Cause == 8, ][,"Cause"] <- "Open Flame"
addresstable[addresstable$Cause == 9, ][,"Cause"] <- "Other Heat"
addresstable[addresstable$Cause == 10, ][,"Cause"] <- "Other Equipment"

addresstable[addresstable$Cause == 11, ][,"Cause"] <- "Natural"
addresstable[addresstable$Cause == 12, ][,"Cause"] <- "Exposure"
addresstable[addresstable$Cause == 13, ][,"Cause"] <- "Unknown"
addresstable[addresstable$Cause == 14, ][,"Cause"] <- "Equipment Misoperation, Failure"
addresstable[addresstable$Cause == 15, ][,"Cause"] <- "Other Unintentional, Careless"
addresstable[addresstable$Cause == 16, ][,"Cause"] <- "Investigation with Arson Module"
```




```{r warning=FALSE,message=FALSE}
library(dplyr)
library(ggmap)
#Add a new column that is the total death of people and firefighters
addresstable <- mutate(addresstable, Total = Other+Firefighter)

#Arrange the columns of the table.
Address_Cause <- select(addresstable, IncidentNO, year, State,City,ZIP, Street, Other, Firefighter, Total, Cause)


require(knitr)
#Presenting the table
kable(head(Address_Cause,15), caption = "Table2",align=c(rep('l',times=9)))

#Save the data to use as table 2 in shiny.
#write.csv(Address_Cause, file="new data/final 1/table2.csv", na="",row.names=FALSE)
```


Get the Longitude and latitude for each data point
```{r}
#Since the data has 6200 observations, it takes really long time to get the longitude and latitude.
#Google restricts the request to 2500 a day so I devide the data into 3 part and search the location.
#I comment out this code. 


#address <- Address_Cause[1:2298,]
#address1 <- Address_Cause[2299:4798,]
#address6200 <- Address_Cause[4799:6200,]
#lonlat <- geocode(as.character(address2500$City))
#write.csv(lonlat, file="new data/location2298.csv", na="",row.names=FALSE)

#lonlat2 <- geocode(as.character(address$City))
#write.csv(lonlat2, file="new data/location4798.csv", na="", row.names=FALSE)

#lonlat3 <- geocode(as.character(address6200$City))
#write.csv(lonlat3, file="new data/location6200.csv", na="", row.names=FALSE)
```



```{r}
#Save the table as CSV file and I will use it in my shiny app.
lonlat <- read.csv("new data/location2298.csv")
#lonlat2 <- read.csv("new data/location4798.csv")
#lonlat3 <- read.csv("new data/location6200.csv")
#lonlat4 <- rbind(lonlat, lonlat2)
location <- cbind(Address_Cause, lonlat)

#write.csv(location, file="new data/final 1/location.csv", na="",row.names=FALSE)

```

############################################################################################################
**Plot**

```{r warning=FALSE,message=FALSE}
library(ggplot2)

location <- read.csv("new data/final 1/location.csv")
#remove the rows that Google doesn't find longitudes and latitudes for. 
location1 <- filter(location, lon != "NA", lat != "NA")
set.seed(4)
#Randomly select samples from the datas
data1 <- sample_n(location1, 500, replace = TRUE)


#Get the map of the United States.
map<-get_map(location='united states', zoom=4, maptype = "terrain",
             source='google',color='color')
g3 <- ggmap(map)+ geom_count(data = data1, aes(color=Cause))

g3


```
